#' @title importArboreto
#' @description Import output from Arboreto/GRNBoost (https://arboreto.readthedocs.io)
#' @param fileName File name of the link/adjacency list
#' @param reorder Whether to sort the links by decreasing weight/importance
#' @seealso pySCENIC (https://pyscenic.readthedocs.io)
#' @examples 
#' GRNBoost_linkList <- importArboreto("adjacencies.tsv")
#' @import data.table
#' @export 
importArboreto <- function(fileName, reorder=FALSE)
{
  arboreto_linkList <- data.table::fread(fileName)
  arboreto_linkList <- as.data.frame(arboreto_linkList)
  colnames(arboreto_linkList) <- R.utils::capitalize(colnames(arboreto_linkList))
  
  if(reorder) arboreto_linkList <- arboreto_linkList[order(arboreto_linkList[,3], decreasing=T),]
  
  return(arboreto_linkList)
}

#' @title importAUCfromText
#' @description Import AUCell matrix from text format, as generated by pySCENIC
#' @param fileName File name of the AUC scores (transposed: gene-sets in rows, cells in columns)
#' @param rows Type of data stored as rows (only for informative purposes) Default: "regulons"
#' @param columns Type of data stored as columns (only for informative purposes) Default: "cells"
#' @param transpose Whether to transpose the input matrix
#' @seealso pySCENIC (https://pyscenic.readthedocs.io)
#' @examples
#' regulonAUC <- importAUCfromText("aucMatrix.tsv")
#' @import data.table AUCell
#' @export
importAUCfromText <- function(fileName, rows="regulons", columns="cells", transpose=TRUE, newNames=NULL)
{
  aucMatrix <- data.table::fread(fileName, drop=1)
  cellNames <- unname(unlist(data.table::fread(fileName, select=1, skip=1)))
  if(transpose) aucMatrix <- t(as.matrix(aucMatrix))
  colnames(aucMatrix) <- cellNames
  if(!is.null(newNames)) rownames(aucMatrix) <- unname(newNames[rownames(aucMatrix)])

  names(dimnames(aucMatrix)) <- c(rows, columns)

  new("aucellResults", SummarizedExperiment::SummarizedExperiment(assays=list(AUC=aucMatrix)))
}


